name: heaven ci comment pr

on: 
  pull_requests:
    paths:
      'hsy3418/*'

jobs: 
  build:
    name: comment on pr
    uses: github-actions-up-and-running/pr-comment@v1.0.0
    with:
      repo-token: ${{ secrets.HH_SECRET_GITHUB_TOKEN }}
      message: Well done ${{secrets.HH_NAME}} This is a nice PR!
