name: lgothelipe-c05-actions02
on:
    pull_request:
      paths: 
          - lgothelipe/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t c05-image:test123 -f lgothelipe/c05-actions02/Dockerfile .
    - name: Log into docker hub
      run: docker login -u ${{ secrets.LG_DOCKER_USERNAME }} -p ${{ secrets.LG_DOCKER_PASSWORD }}
    - name: Push image
      run: |
        docker tag c05-image:test123 ${{ secrets.LG_DOCKER_USERNAME }}/c05-image:test123
        docker push ${{ secrets.LG_DOCKER_USERNAME }}/c05-image:test123
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.LG_GITHUB_TOKEN }}
          message: Image name c05-image:test123
          allow-repeats: false
