name: lgothelipe-c05-actions02
on:
    pull_request:
      paths: 
          - lgothelipe/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SHORT_SHA: ${{ github.sha }}
        IMAGE_NAME: ${{ 'c05-image' }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t $IMAGE_NAME:test122 -f lgothelipe/c05-actions02/Dockerfile .
    - name: Log into docker hub
      run: docker login -u ${{ secrets.LG_DOCKER_USERNAME }} -p ${{ secrets.LG_DOCKER_PASSWORD }}
    - name: Push image
      run: |
        docker tag $IMAGE_NAME:test122 ${{ secrets.LG_DOCKER_USERNAME }}/$IMAGE_NAME:test122
        docker push ${{ secrets.LG_DOCKER_USERNAME }}/$IMAGE_NAME:test122
  comment:
    runs-on: ubuntu-latest
    env:
        SHORT_SHA: ${{ github.sha }}
        IMAGE_NAME: ${{ 'c05-image' }}   
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.LG_GITHUB_TOKEN }}
          message: Image name $IMAGE_NAME:$SHORT_SHA
          allow-repeats: false
