name: PR Comments
on: 
  pull_request: 
    paths: 
        - starkmatt/**
jobs:
  PR-Commenter:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
            message: Great PR Matteh!
            GITHUB_TOKEN: ${{ secrets.SM_GIT_HUB_TOKEN }}
            allow-repeats: false 
